name: Lua linter

on:
  push:
  pull_request:
  workflow_dispatch:

# TODO: Move to selfhost runner
jobs:
  lua_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Luacheck
        uses: lunarmodules/luacheck@v1.1.0

